### ISSUE TITLE
kaklan.cf isn't working

### ISSUE THREAD

**Issue by gk-git** [kevinabouhanna/batata-harra-webring#4]
The URL for Jiro card isn't working

**Comment by kevinabouhanna** [comment]
@jiroachkarian I have removed kaklan from the repo and from webring.json, create a new repo and submit a pull request with a working link please

**Comment by kevinabouhanna** [comment]
2f8755aed1b17f242f7736283ed590a772c1abbd

**Comment by jiroachkarian** [comment]
https://github.com/jiroachkarian/jiroachkarian.github.io this is my new repo
